framework:
    messenger:
        buses:
            command_bus: ~
            event_bus:
                default_middleware: 'allow_no_handlers'

        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'App\Message\Lost': amqp
