framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus: ~
            event_bus: ~

#        transports:
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\Lost': amqp
            # 'App\Message\Won': amqp
