framework:
    messenger:
        buses:
            command_bus:
                middleware:
                - 'App\Middleware\AuditMiddleware'
            event_bus:
                middleware:
                - 'App\Middleware\AuditMiddleware'
                default_middleware: 'allow_no_handlers'

        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'App\Message\Lost': amqp
