framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                    - 'App\Middleware\AuditMiddleware'

            event_bus: ~

        transports:
            transport_name: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'App\Message\Lost': transport_name
            'App\Message\Won': transport_name
