framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                    - 'App\Middleware\AuditMiddleware'

            event_bus:
                middleware:
                    - 'App\Middleware\AuditMiddleware'

        failure_transport: failure

        transports:
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 2

            failure: doctrine://default?queue_name=failures

        routing:
            # Route your messages to the transports
            'App\Message\Lost': amqp
            'App\Message\Won': amqp
